<?php

/**
 * @file
 * Primary module hooks for os2web_meetings module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\os2web_meetings\Form\SettingsForm;

/**
 * Implements hook_form_alter().
 */
function os2web_meetings_acadre_form_os2web_meetings_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['acadre_meetings_import_details'] = [
    '#type' => 'details',
    '#title' => t('Acadre Import settings'),
  ];

  $form['acadre_meetings_import_details']['acadre_meetings_manifest_path'] = [
    '#type' => 'textfield',
    '#title' => t('Acadre Meetings manifests path'),
    '#description' => t('Example: public://acadre'),
    '#default_value' => \Drupal::config(SettingsForm::$configName)
      ->get('acadre_meetings_manifest_path'),
  ];
}
